[supabase]
url = "https://nizydgmnlmfiojcdrnwx.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5penlkZ21ubG1maW9qY2Rybnd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNjczNDMsImV4cCI6MjA2Mzc0MzM0M30.bDu40yJbEROYibqXIx_IQ9IP-j5fFwZAn35y7g0BBxA"